let peliculas = [
  {
    nombre: "Soy Groot",
    imagen: "images/yo_soy_groot.jpg",
    categoria: "Aventura",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Zootopia",
    imagen: "images/zootopia.jpg",
    categoria: "Aventura",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "UP",
    imagen: "images/up.jpg",
    categoria: "Aventura",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Winnie Poh",
    imagen: "images/winnie_pooh.jpg",
    categoria: "Aventura",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Logan",
    imagen: "images/logan-accion.jpg",
    categoria: "Accion",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Iron Man",
    imagen: "images/iron_man-accion.jpg",
    categoria: "Accion",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Doble de riesgo",
    imagen: "images/doble_de_riesgo-accion.jpg",
    categoria: "Accion",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "John Wick 4",
    imagen: "images/john-wick-accion.jpg",
    categoria: "Accion",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "El Ninio",
    imagen: "images/el-nino-terror.jpg",
    categoria: "Terror",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "La huerfana",
    imagen: "images/la-huerfana-terror.jpg",
    categoria: "Terror",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Mama",
    imagen: "images/mama-terror.jpg",
    categoria: "Terror",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Huesera",
    imagen: "images/huesera-terror.jpg",
    categoria: "Terror",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Missy",
    imagen: "images/missy-comedia.jpg",
    categoria: "Comedia",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Delivery Man",
    imagen: "images/delivery-comedia.jpg",
    categoria: "Comedia",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "dover",
    imagen: "images/dover-comedia.jpg",
    categoria: "Comedia",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Una comedia macabra",
    imagen: "images/comedia-macabra-comedia.jpg",
    categoria: "Comedia",
    codigo: "",
    descripcion: "",
    publicado: true,
  },
];
