let peliculas = [
  {
    nombre: "Soy Groot",
    imagen: "/images/yo_soy_groot.jpg",
    categoria: "Aventura",
    codigo: 0,
    descripcion:
      "asdasdasdsadasdsadsadsadasdasdsadadasdsadsadsadasdaadasdsadsadsadasda",
    publicado: true,
    destacada: true,
  },
  {
    nombre: "Zootopia",
    imagen: "images/zootopia.jpg",
    categoria: "Aventura",
    codigo: 1,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "UP",
    imagen: "images/up.jpg",
    categoria: "Aventura",
    codigo: 2,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "Winnie Poh",
    imagen: "images/winnie_pooh.jpg",
    categoria: "Aventura",
    codigo: 3,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "Logan",
    imagen: "images/logan-accion.jpg",
    categoria: "Accion",
    codigo: 4,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "Iron Man",
    imagen: "images/iron_man-accion.jpg",
    categoria: "Accion",
    codigo: 5,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "Doble de riesgo",
    imagen: "images/doble_de_riesgo-accion.jpg",
    categoria: "Accion",
    codigo: 6,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "John Wick 4",
    imagen: "images/john-wick-accion.jpg",
    categoria: "Accion",
    codigo: 7,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "El Ninio",
    imagen: "images/el-nino-terror.jpg",
    categoria: "Terror",
    codigo: 8,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "La huerfana",
    imagen: "images/la-huerfana-terror.jpg",
    categoria: "Terror",
    codigo: 9,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "Mama",
    imagen: "images/mama-terror.jpg",
    categoria: "Terror",
    codigo: 10,
    descripcion: "",
    publicado: true,
  },
  {
    nombre: "Huesera",
    imagen: "images/huesera-terror.jpg",
    categoria: "Terror",
    codigo: 11,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "Missy",
    imagen: "images/missy-comedia.jpg",
    categoria: "Comedia",
    codigo: 12,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "Delivery Man",
    imagen: "images/delivery-comedia.jpg",
    categoria: "Comedia",
    codigo: 13,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "dover",
    imagen: "images/dover-comedia.jpg",
    categoria: "Comedia",
    codigo: 14,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
  {
    nombre: "Una comedia macabra",
    imagen: "images/comedia-macabra-comedia.jpg",
    categoria: "Comedia",
    codigo: 15,
    descripcion: "",
    publicado: true,
    destacada: false,
  },
];
